//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScannerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cv
    {
        public int Cv_Id { get; set; }
        public byte[] Cv_Doc { get; set; }
        public int Stud_Id { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
